#!/usr/local/bin/node
// ^^ The tasks command file should have a shebang pointing to node
// shebang tells you what interpreter to use to run the file
// could also be #!/usr/bin/env node

// The add command is implemented in ./commands/add.js
const add = require('./add');
// The complete command is implemented in ./commands/complete.js
const comp = require('./complete');
// The delete command is implemented in ./commands/delete.js
const del = require('./delete');
// The list command is implemented in ./commands/list.js
const list = require('./list');
// assign task instructions to command and task
const command = process.argv[2];
// instead of 'const task = process.argv[3]' -- take all input from 3 on
const task = process.argv.slice(3).join(' ');

switch (command) {
  case 'add':
    add.add(task);
    break;
  case 'list':
    list.list();
    break;
  case 'delete':
    del.del(task);
    break;
  case 'complete':
    comp.comp(task);
    break;
  default:
    // User receives an error message if they enter an invalid command
    console.log('Missing or invalid command');
}
