#!/usr/local/bin/node
// ^^ The tasks command file should have a shebang pointing to node
// shebang tells you what interpreter to use to run the file
// could also be #!/usr/bin/env node

// The following four commands are located in the ./commands/ directory
const add = require('./commands/add');
const comp = require('./commands/complete');
const del = require('./commands/delete');
const list = require('./commands/list');
// assign task instructions to command and task
const command = process.argv[2];
// instead of 'const task = process.argv[3]' -- take all input from 3 on
const task = process.argv.slice(3).join(' ');

if (command !== undefined) {
  if (command === 'list') {
    list();
  } else if (task !== '') {
    switch (command) {
      case 'add':
        add(task);
        break;
      case 'delete':
        del(task);
        break;
      case 'complete':
        comp(task);
        break;
      default:
        console.log('  Invalid command- options are "add", "delete", "complete", and "list"');
    }
  } else {
    console.log('  Missing task or task number');
    console.log('  - "add" should be followed by a task description');
    console.log('  - "delete" and "complete" should be followed by a task number');
  }
} else {
  console.log('  Missing command - options are "add", "delete", "complete", and "list"');
}
